name: PR Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      dependencies: ${{ steps.filter.outputs.dependencies }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3
        id: filter
        with:
          filters: |
            dependencies:
              - '**/libs.versions.toml'
              - '**/build.gradle.kts'
              - '**/build.gradle'

  build:
    uses: ./.github/workflows/build.yml

  detekt:
    uses: ./.github/workflows/detekt.yml

  unit-tests:
    needs: build
    uses: ./.github/workflows/unit-tests.yml

  dependency-check:
    needs: changed-files
    if: needs.changed-files.outputs.dependencies == 'true'
    uses: ./.github/workflows/dependency-check.yml
    secrets: inherit
